name: Verify Storybook

on:
  pull_request:
    paths:
      - 'packages/grafana-ui/**'
      - '.github/workflows/storybook-verification.yml'
      - '!docs/**'
      - '!*.md'

jobs:
  verify-storybook:
    name: Verify Storybook
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --immutable
      
      - name: Run Storybook and E2E tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: yarn storybook --quiet
          wait-on: 'http://localhost:9001'
          wait-on-timeout: 60
          command: yarn e2e:storybook
          install: false
        env:
          HOST: localhost
          PORT: 9001
